alias gits='git status -bs'
alias gitm='git commit -m'
alias gitam='git add . ; git commit -m'
alias gitnb='git checkout master; git pull origin master; git checkout -b'
alias mkdirc='function _(){ mkdir $1 ; cd $1; }; _'
